name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: gcc:11.4.0

    steps:
    - uses: actions/checkout@v4
    - name: day01
      working-directory: ./day01
      run: make test
    - name: day02
      working-directory: ./day02
      run: make test
